### ISSUE TITLE
mattress/product - implement 'zero disturbance' looping background video

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#12]

**Comment by joeldrobertson2** [comment]
I've set up a basic implementation of this with the mp4 file provided. There is an image displayed until the video loads. But it does take quite a while before the video loads and it can start playing.

Would it be possible to upload the video to your vimeo account so I can try streaming it from there? Or also we could try compressing the video more so it is smaller in file size.

**Comment by ohnno** [comment]
Hey mate,

Happy to do whatever is needed - if it needs to go on vimeo that's fine. You can even compress it before putting it on vimeo if you want, the quality does not need to be perfect since it's just a textural video.

I'll just give you a link to vimeo to make things easier:

greywingmattress@gmail.com
LLGqIguGtyFNO6p

**Comment by joeldrobertson2** [comment]
Thanks Johnny

**Comment by joeldrobertson2** [comment]
Vimeo isn't going to work here unfortunately unless you upgrade to a pro account. I've used the supplied mp4 but it would be great to compress it to a smaller size if that's possible. Would you be able to get that organised?

**Comment by ohnno** [comment]
We have a paid wistia account that we could use actually, and that was being used on the old site for those types of videos.

I'm asking for the login now and will send it when I have it.
