### ISSUE TITLE
mattress/buy - 'add to cart' button's hover state icon is incorrect.

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#14]

**Comment by ohnno** [comment]
refer to PSD 'global interaction' for list of icons for these buttons.

**Comment by joeldrobertson2** [comment]
Sorry it should be a plus sign shouldn't it?

**Comment by ohnno** [comment]
yep! :)

**Comment by joeldrobertson2** [comment]
This has been changed to the correct icon.

**Comment by ohnno** [comment]
Hey Joel, is this a plus now? On my screen I saw a tick when I checked five minutes ago and now it's a price tag!

**Comment by joeldrobertson2** [comment]
Sorry about the confusion. It is definitely a plus now

**Comment by ohnno** [comment]
Lol sorry Joel but this only seems to have changed on the Mattress page and not the Sheets page!
