### ISSUE TITLE
mattress/buy - add missing gallery images

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#21]
mattress-product-adaptive.jpg
mattress-product-hero.jpg

**Comment by joeldrobertson2** [comment]
I've added the missing gallery images: https://grey-wing.myshopify.com/products/buy-mattresses-online
Although the cropped images don't look so great on desktop. 

Should the gallery break of the grid and align to the top left of the screen?

![image](https://cloud.githubusercontent.com/assets/19680256/16072076/4a2805b4-3322-11e6-9a0f-cce2a95af45a.png)
![image](https://cloud.githubusercontent.com/assets/19680256/16072087/560beba2-3322-11e6-89b3-9c389897ded8.png)

**Comment by ohnno** [comment]
Yeah I'd like to play around with the scaling etc on desktop - but for now this is fine! Thanks
