### ISSUE TITLE
reviews - not all reviews are showing; pagination missing.

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#22]

**Comment by joeldrobertson2** [comment]
I've used javascript to filter the reviews when the dropdown is changed. Mattress reviews are shown by default.

The form will need to identify what product customers are reviewing so we can sort them on this page. The only way I can see this happening is if customers select which product they are reviewing in the wufoo form. 

I'll also need to find out how the wufoo form outputs the tags for reviews that Tom selects and make sure that a new review type tag is added.

**Comment by ohnno** [comment]
Hey mate, sorry for the delayed response to this but here's an update:

- The reviews are currently being entered manually via the CMS (following a specific format)
- We're happy for it to keep following this process unless you guys are happy to automate it.
- For the time being, we'll only need to keep adding mattress reviews - once we need reviews for other products too, these will probably be separate wufoo forms.
- I don't think the "write review" button should be dynamic, they should choose the product they want to review after they click "write review". This is not something you guys need to worry about.

I'm not sure what you mean by the output tags, can you clarify?

**Comment by joeldrobertson2** [comment]
This all sounds OK. I've implemented the reviews so they will work with your current process. 

The tags I am talking about are what is currently used to mark up the reviews and feed them into the review template. They look like this.

[date]20 May 2016[/date] 
[time]6:30 PM[/time]
[rating]0[/rating]
[name]Karen B[/name]
[title]Well Rested & Happy![/title]

To sort the reviews I have added a new tag: [review-type][/review-type]
This will wrap each product type:

[review-type]review-mattress[/review-type]
[review-type]review-sheets[/review-type]
[review-type]review-pillow[/review-type]
[review-type]review-bed-base[/review-type]

This corresponds to the select field on the reviews page and allows it to show the relevant reviews

**Comment by ohnno** [comment]
Great I think this is fine!
