### ISSUE TITLE
reviews - implement 'write a review' button

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#23]

**Comment by joeldrobertson2** [comment]
Will this launch the wufoo review form in a modal window? If so would you like to try and style the wufoo form or just leave it as is?

**Comment by ohnno** [comment]
yep this will launch wufoo form (I can't remember if it was a new tab of modal window). I'd be happy if we could try and style it but it isn't a huge priority, what are our options for doing that?

**Comment by joeldrobertson2** [comment]
The write review button now links to a page with the wufoo form embedded. There is still a possibility of styling the form but will have to leave that for later.
