### ISSUE TITLE
faq - implement faq mockup

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#26]

**Comment by ohnno** [comment]
faq page mockup has now been provided in the contemplate v1f+

dropdown will have the following:

1. TOP QUESTIONS
2. SIZING & COMPATIBILITY
3. MATERIALS & CONSTRUCTION
4. SHIPPING & RETURNS
5. PURCHASING EXPERIENCE
6. CERTIFICATIONS & POLICIES
7. FOR GREYWING OWNERS

breakdown of these sections will follow in comments below

**Comment by joeldrobertson2** [comment]
This is ready now. Although I will still need to add the new content.

**Comment by joeldrobertson2** [comment]
The heading hierarchy has been fixed and new content added.
