### ISSUE TITLE
reviews - design refinements

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#29]

**Comment by ohnno** [comment]
sorry to change this but after looking at the implementation it's looking rather messy.

I made some relatively minor changes to the layout of this page, please in the current PSD's in v1j+

reference attached

![screenshot](https://cloud.githubusercontent.com/assets/2937538/15954645/e3140048-2f1c-11e6-8fae-3164a0417747.jpg)

**Comment by joeldrobertson2** [comment]
I've completed this and it's on the development store!

**Comment by joeldrobertson2** [comment]
I've checked against the artwork and found the headings were too large. They have been changed to 32 pixels.
