### ISSUE TITLE
reviews - chat about implementation of reviews across the site

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#30]
Right now it seems like the reviews page is linked to the review sections on other pages, this is not according to the original spec.

Here's how it should work:
- The review sections on separate pages should have 4-5 hard coded reviews, the reason for this is so that we can hand pick the feature reviews on these pages, have a different set of reviews on each page, and also control the length of each review so that we can standardize the height of that section. You're welcome to link them to the full list of reviews if you want but it seems like more effort than it's worth!
- The review page should have the full list of reviews.

Let me know if that's confusing and we can chat about it.

**Comment by joeldrobertson2** [comment]
I have placed a few reviews from the reviews page in the review sections. Just let me know which reviews are required and I can drop them in.

Also on the reviews it looks like they are submitted via a wufoo form. Then manually selected and placed in the shopify page. Is that right?

Would you like the wufoo review form to be triggered in a modal window when the reviews button is clicked?

**Comment by ohnno** [comment]
Yes that's correct, they are placed via the CMS via inputting the info via a specific formatting method. The scope was to continue to use that process.

I'll figure out with Tom which reviews we want on each page.
