### ISSUE TITLE
mattress/product/responsive/large - move hero image as far to right as possible (full image not being shown right now)

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#32]

**Comment by joeldrobertson2** [comment]
Are you referring to the images at the top of the page here?

![image](https://cloud.githubusercontent.com/assets/19680256/16180985/d8ca0b16-36d6-11e6-8905-cf57f91c58d1.png)

**Comment by ohnno** [comment]
Yep, this is only an issue on larger screens - the image looks very far off to the left.

![screenshot-2](https://cloud.githubusercontent.com/assets/2937538/16181015/916f2caa-36d7-11e6-8b56-f15d56cfb300.png)

But at the same time, the entire image is not being shown:

![screenshot-1](https://cloud.githubusercontent.com/assets/2937538/16181017/9fe62068-36d7-11e6-8375-d9439450343e.png)

I'm thinking the easiest way to resolve this could be to add a media query for large screen sizes where more of the image is shown?
