### ISSUE TITLE
home - implement mattress interactive animation

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#4]

**Comment by joeldrobertson2** [comment]
Hi Johnny. This is up and running on the development site now! https://grey-wing.myshopify.com
I've expanded the container so the mattress responds to the full size of the screen.

**Comment by ohnno** [comment]
Thanks Joel,
This is still responding to an area for me and not the full width of the window. Also can we please remove the pointer change? It's changing to a hand when it's in the area.

This isn't urgent so we don't need to address it right away but ideally this would respond to the full window when the cursor is in that section (if possible).

**Comment by joeldrobertson2** [comment]
OK I've removed the grab cursor and shifted the mattress animation outside of the page container so it fills the full width of the screen.
