### ISSUE TITLE
header - add a 'buy now' item + implement the '•' divider

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#43]
now that we have sheets it would be good to get the divider in there.

reference for the 'buy' now attached - is it possible for this item to just not show in the responsive menu?

![screenshot](https://cloud.githubusercontent.com/assets/2937538/15952000/898c4aec-2f00-11e6-8c71-dfba8b146898.jpg)

**Comment by joeldrobertson2** [comment]
Updated on the development store: https://grey-wing.myshopify.com/
