### ISSUE TITLE
home - change hero image + implement play button style + change text

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#44]
change the hero image to [home-hero-new]

change "starts with greywing" to "starts with your mattress"

implement play button style

reference attached

![screenshot-1](https://cloud.githubusercontent.com/assets/2937538/15952052/0e418bda-2f01-11e6-885f-9465c12a8304.jpg)

**Comment by joeldrobertson2** [comment]
Updated on the development store: https://grey-wing.myshopify.com/
