### ISSUE TITLE
global - promo banner

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#50]
can we implement a promo banner with the following specs?

- locked to the bottom of the header
- can be closed

image assets are in the latest main PSD file

here are some mockups for the design, let me know if there are any issues or concerns:
![eofy-mockup-desktop](https://cloud.githubusercontent.com/assets/2937538/16065486/8c8e6774-32ee-11e6-842c-ac2a39d6c84d.jpg)
![eofy-mockup-tablet](https://cloud.githubusercontent.com/assets/2937538/16065489/9016da5c-32ee-11e6-9351-149df642de5b.jpg)
![eofy-mockup-mobile](https://cloud.githubusercontent.com/assets/2937538/16065491/930e3d9a-32ee-11e6-99b9-76caaacc74fa.jpg)

**Comment by ohnno** [comment]
![eofy-banner-image](https://cloud.githubusercontent.com/assets/2937538/16065506/b5fe4ac0-32ee-11e6-9089-ba0ede14c933.png)
![eofy-close-button](https://cloud.githubusercontent.com/assets/2937538/16065507/b6001b8e-32ee-11e6-9309-a00e3a6e6211.png)



image assets

**Comment by joeldrobertson2** [comment]
The new banner is ready!

**Comment by ohnno** [comment]
Hey mate this looks great!

Unfortunately that particular sale is over for now, but can you provide a quick reference for the dev if we wanted to turn this on and off on demand? And also change the text/image.
