### ISSUE TITLE
sheets - implement pre-order text

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#52]
implement a psuedo pre-order function, the actual functionality will be exactly the same (orders will go through as normal), but we'd like to add some text - not sure what's possible to achieve easily but I'll add best case and worst case scenarios - first, here's the mockup.

![screenshot](https://cloud.githubusercontent.com/assets/2937538/16065934/52f00cf8-32f2-11e6-898d-9ec0455a5572.jpg)

BEST CASE
Only when White/Grey is selected, button text will change to PREORDER and text below will appear.

WORST CASE
Button text stays ADD TO CART. Preorder text will always be visible.

Let me know if any questions or concerns. Again this is only some text changes, no changes to functionality.

**Comment by joeldrobertson2** [comment]
This is live on the site now.
