### ISSUE TITLE
showroom - replace text with calendly embed

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#58]

**Comment by joeldrobertson2** [comment]
Johnny I'm not 100% sure what to do here. You might have to run me though it.

**Comment by ohnno** [comment]
Hey mate, you don't have to worry about the stuff assigned to me.

But for reference, Tom was wanting to embed the calendly widget into the showroom page, and this task was for me to mock it up.

**Comment by joeldrobertson2** [comment]
Oh of course. My bad. I'm just trying to make sure I'm on top of everything that needs to be completed.

**Comment by ohnno** [comment]
I've updated the content-template (v1g) with the mockup for this. It should be very simple, just replacing the text/button at the bottom with an embed snippet:


<div class="calendly-inline-widget" data-url="https://calendly.com/greywing" style="min-width:320px;height:580px;"></div>
<script type="text/javascript" src="https://calendly.com/assets/external/widget.js"></script>


Screenshot attached for reference:
![screenshot](https://cloud.githubusercontent.com/assets/2937538/16548610/4fa7e762-41d6-11e6-8780-2e2a5b5df0fa.png)

**Comment by ohnno** [comment]
Sorry I just realized the code snippet I pasted wasn't showing, fixed this now

**Comment by joeldrobertson2** [comment]
I've added this widget to the page but was unable to float the two columns as in the artwork.
