### ISSUE TITLE
sheets pages - reinstate hidden content sections and update their copy

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#60]
hey guys is it a quick thing to unhide the missing content sections on the sheets pages? we have copy for them now.

Please find attached mockups - the new copy is in the latest PSD

![screenshot-1](https://cloud.githubusercontent.com/assets/2937538/16066403/4edd426c-32f6-11e6-8ec1-f36a2463a486.jpg)
![screenshot](https://cloud.githubusercontent.com/assets/2937538/16066404/501e95fe-32f6-11e6-92b4-908d6b6691ce.jpg)

**Comment by joeldrobertson2** [comment]
I've updated this content now.
