### ISSUE TITLE
cart - giant checkout button bug

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#61]
this has happened a few times in firefox, but I don't know how to reproduce the issue.... refreshing the page fixes it - any ideas?
 
![screenshot-2](https://cloud.githubusercontent.com/assets/2937538/16071312/0279529e-331e-11e6-83f5-cf3bbd7d67e9.jpg)

**Comment by joeldrobertson2** [comment]
I've discovered a bug in my code that could potentially cause the font size to be 700 pixels. The rule was intended for font weight but accidentally affecting the font size on rare occasions.

**Comment by joeldrobertson2** [comment]
Johnny should the update cart button icon be a tick instead of a plus?

![image](https://cloud.githubusercontent.com/assets/19680256/16138708/c018483a-3483-11e6-8cfb-ed6ec7dd3d43.png)

**Comment by ohnno** [comment]
We are planning to have this update via AJAX eventually right?

Happy to just use a tick in the meantime
