### ISSUE TITLE
home/responsive/mobile - disable rotating mattress on mobile

### ISSUE THREAD

**Issue by tbrown123** [ohnno/Greywing#64]
on mobile if you scroll down and have the mattress at the bottom of the screen you cannot scroll the screen. you need to swipe above it to make it move. I understand, however a less capable user will leave.

**Comment by joeldrobertson2** [comment]
It might be possible to only move the mattress when a user moves horizontally and keep vertical movements for scrolling. Will disable for now.

**Comment by ohnno** [comment]
Ah that would be cool! I'll leave it with you then, thanks mate

**Comment by joeldrobertson2** [comment]
I've disabled movements on mobile for the moment until I figure that one out.

**Comment by joeldrobertson2** [comment]
I've enabled this again on mobile and also allowed scrolling.
