### ISSUE TITLE
Order Confirmation Page - Copy Error

### ISSUE THREAD

**Issue by tbrown123** [ohnno/Greywing#66]
Currently the page says: "come back to this page for updates on your order". This needs to be removed and it should say. "You'll also receive an email with tracking details."

<img width="897" alt="screenshot 2016-06-18 17 05 42" src="https://cloud.githubusercontent.com/assets/19923735/16222059/866c7062-37d9-11e6-9312-7aee7fb1ab8c.png">

**Comment by joeldrobertson2** [comment]
I don't think this will be an issue with the new checkout design as most of the shopify content has been removed.
