### ISSUE TITLE
Sheet FAQ

### ISSUE THREAD

**Issue by tbrown123** [ohnno/Greywing#67]
Please get the sheet FAQ onto the site.

[SHEET FAQ.docx](https://github.com/ohnno/Greywing/files/332847/SHEET.FAQ.docx)

**Comment by ohnno** [comment]
Note that the sheets mockup https://github.com/ohnno/Greywing/issues/26 has not been implemented yet - you might want to do that first.

**Comment by joeldrobertson2** [comment]
I've added these to the bottom of the FAQ page and also included a link in the dropdown.
