### ISSUE TITLE
FAQ Updates

### ISSUE THREAD

**Issue by tbrown123** [ohnno/Greywing#68]
Please update and make these additions for the FAQ

[FAQ Addition.docx](https://github.com/ohnno/Greywing/files/336260/FAQ.Addition.docx)

**Comment by ohnno** [comment]
note that the FAQ mockup https://github.com/ohnno/Greywing/issues/26 has not been implemented yet - you might want to do that first.

**Comment by joeldrobertson2** [comment]
These have been added to the FAQ page.
