### ISSUE TITLE
global - standardize 'review' module height; stop arrows from moving

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#7]
- set the height of the module to be fixed so that it doesn't change between reviews
- set the position of the arrows to be fixed so they don't move between reviews

**Comment by ohnno** [comment]
Let's work through this together,

**Comment by joeldrobertson2** [comment]
I've set the height of the review module to be the tallest slide. This will stop the arrows from moving and also improve the transition between slides as the container won't be changing sizes.
