### ISSUE TITLE
contact - implement contact page as per mockup

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#70]
I think this may have been forgotten since this was sent through before github via email.

There's a mockup for the contact page in the content-template psd.

**Comment by ohnno** [comment]
Chat button:
 - Yeah we have a zendesk widget (the help button on the bottom right). I'm not too fussed exactly what opens, whatever is easier - whether it's opening the bottom right chat widget, or opening a popup chat window (I'm not sure what options zendesk comes with). In any case let me know if you need anything from me.

Phone button:
Yeah I think that's fine!

**Comment by joeldrobertson2** [comment]
I've made the contact button activate the zendesk widget on a click.
