### ISSUE TITLE
sheets/product - refine hero image responsive

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#71]
Can we have this hero sheets hero image show in the same way that the mattress hero image shows on the mattress page?

Right now it seems to be showing differently, the sheets one seems to scale and become pixelated, as opposed to the mattress one which is fixed but reveals horizontally when the browser expands.

Screenshots attached for reference:
![screenshot](https://cloud.githubusercontent.com/assets/2937538/16548932/18e6332c-41dc-11e6-8cda-c124abdf201c.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/2937538/16548934/1a961ab6-41dc-11e6-8990-f0eeb9ec8c02.png)

**Comment by joeldrobertson2** [comment]
I've applied similar styles to the mattress hero.
