### ISSUE TITLE
promo banner - turn back on with new content

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#73]
Can we please turn the eofy promo banner you did but with the following text and image:

Want to try our mattress in Melbourne? Showroom Hours: 9am-5pm Mon-Fri & Sat 10am-4pm. Book Here

![showroom-banner-image](https://cloud.githubusercontent.com/assets/2937538/16607519/2d4dc42e-4385-11e6-9d2f-6f138f7b0562.png)

Make the 'Book Here' bold and colored aqua.

Let me know if any questions!

**Comment by joeldrobertson2** [comment]
Image and text have been aligned left.
