### ISSUE TITLE
"The Greywing Difference" still needs more spacing above on large screens

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#76]
see screenshot for reference

27 inch screen
![screenshot-5](https://cloud.githubusercontent.com/assets/2937538/16607616/7158fbe2-4386-11e6-8c40-284c68678451.png)

21.5 inch screen
![screenshot-7](https://cloud.githubusercontent.com/assets/2937538/16607618/7adc6208-4386-11e6-9c79-3ad87848d4a6.png)

**Comment by joeldrobertson2** [comment]
This was quite tricky to get right! I've used vertical width units on the padding which are relative to the width of the screen. As the screen gets wider the padding is increased. Let me know if there are any breakpoints where the spacing is outside of reasonable tolerances.

**Comment by ohnno** [comment]
No this is great, thanks for figuring it out!
