### ISSUE TITLE
shop page gallery thumbnails are tiny and aligned a little weird across screen sizes

### ISSUE THREAD

**Issue by ohnno** [ohnno/Greywing#77]
see screenshot for reference:

![screenshot-8](https://cloud.githubusercontent.com/assets/2937538/16607640/d877a4fe-4386-11e6-977a-7ed78a1587e9.png)

![screenshot-10](https://cloud.githubusercontent.com/assets/2937538/16607693/81d13254-4387-11e6-869d-fafb2c16aeff.png)

I think part of the problem is that I've noticed the images are different sizes:
![screenshot-9](https://cloud.githubusercontent.com/assets/2937538/16607648/e68e9872-4386-11e6-9563-9b59dd66e5a4.png)

The thumbs need to be bigger (refer to the original designs) and alignment needs to be refined.

I also noticed that the sheets page seems to be looking better (and slightly different to the mattress page)

I'm happy to resupply images, just let me know how you want them. Are the thumbnails separate images or do they have to be the same image as the main gallery image?

Let me know, cheers!

**Comment by joeldrobertson2** [comment]
Hi Johnny. Sorry about the problems here. I've reworked the slider css and fixed most of the bugs.

The thumbs are generated from the main images. If you supply thumbs I could hard code them but then you would lose the ability to update product images through shopify. I will see if it's possible to generate thumbs at a different aspect ratio.

**Comment by ohnno** [comment]
No I think this is fine!
